---
- name: Updating Homebrew
  homebrew:
    update_homebrew: true
  when: homebrew_check.stat.exists

- name: Upgrading Homebrew Packages
  homebrew:
    upgrade_all: "{{ upgrade_homebrew_packages }}"
  register: result
  until: result is successful
  when: homebrew_check.stat.exists

- name: Installing Homebrew Cask Packages
  homebrew_cask:
    name: "{{ homebrew_cask_packages }}"
    state: present
    install_options: 'appdir={{ homebrew_cask_app_dir }}'
  register: result
  until: result is successful
  when: homebrew_check.stat.exists

- name: Installing Homebrew Packages
  homebrew:
    name: "{{ homebrew_packages }}"
    state: present
  register: result
  until: result is successful
  when: homebrew_check.stat.exists
